FROM python:3.13-slim

RUN apt-get update && apt-get install -y \
    curl \
    git \
    gnuplot

# Copy requirements file and install packages
COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt && pip install -U scikit-fuzzy